### PR TITLE
fix: panic/error handling while enumerating pins

### LINKED ISSUE #14: panic: runtime error: index out of range [-1]
Panic with go-ipfs 0.12 while doing `ipfs pin remote ls --service=estuary --status=queued`

```
Daemon is ready
panic: runtime error: index out of range [-1]

goroutine 113809296 [running]:
github.com/ipfs/go-pinning-service-http-client.(*Client).Ls.func1(0xc0bceda900, 0xc0bceda8a0, 0xc051651d58, 0x264b078, 0xc070f03b00, 0xc0bceda960)
	github.com/ipfs/go-pinning-service-http-client@v0.1.0/client.go:179 +0x509
created by github.com/ipfs/go-pinning-service-http-client.(*Client).Ls
	github.com/ipfs/go-pinning-service-http-client@v0.1.0/client.go:154 +0x1b5
```
Seems that: 
https://github.com/ipfs/go-pinning-service-http-client/blob/133fb5347ddc144063d2e7e88e8c37ed8f8fd60c/client.go#L179

fails super hard because of missing results:

```console
$ curl  -H "Authorization: Bearer [secret]" "https://api.estuary.tech/pinning/pins?status=queued"
{"count":15,"results":null}
```

### PR DESCRIPTION
**Pull request by lidel**
This PR aims to close #14 by fixing batch enumeration + adding panic recovery just in case.

Proper e2e sharness tests live in go-ipfs, so I opened a PR draft there too: https://github.com/ipfs/go-ipfs/pull/8894

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -153,8 +153,22 @@ func (c *Client) Ls(ctx context.Context, opts ...LsOption) (chan PinStatusGetter
...
+				case error:
+					err = fmt.Errorf("unexpected error while listing remote pins: %w", x)
+				default:
+					err = errors.New("unknown panic while listing remote pins")
+				}
+				errs <- err
+			}
+			close(errs)
+			close(res)
+		}()
```
Comment (lidel) [inline client.go:171]: Is this ok or overkill?

Comment (Jorropo) [reply client.go:171]: SGTM

Maybe we should wrap this in a wrapper package ? Like the `multierror.Group`.

**Review by Jorropo — APPROVED** [review]
LGTM
